In [1]:
import numpy as np

In [3]:
x = np.linspace(1,100,100)
x.resize(10,10)
x

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [9]:
z = x*3
z

array([[  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.],
       [ 33.,  36.,  39.,  42.,  45.,  48.,  51.,  54.,  57.,  60.],
       [ 63.,  66.,  69.,  72.,  75.,  78.,  81.,  84.,  87.,  90.],
       [ 93.,  96.,  99., 102., 105., 108., 111., 114., 117., 120.],
       [123., 126., 129., 132., 135., 138., 141., 144., 147., 150.],
       [153., 156., 159., 162., 165., 168., 171., 174., 177., 180.],
       [183., 186., 189., 192., 195., 198., 201., 204., 207., 210.],
       [213., 216., 219., 222., 225., 228., 231., 234., 237., 240.],
       [243., 246., 249., 252., 255., 258., 261., 264., 267., 270.],
       [273., 276., 279., 282., 285., 288., 291., 294., 297., 300.]])

In [11]:
np.save('div_by_3.npy', z)

In [13]:
j = np.load('div_by_3.npy')
j

array([[  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.],
       [ 33.,  36.,  39.,  42.,  45.,  48.,  51.,  54.,  57.,  60.],
       [ 63.,  66.,  69.,  72.,  75.,  78.,  81.,  84.,  87.,  90.],
       [ 93.,  96.,  99., 102., 105., 108., 111., 114., 117., 120.],
       [123., 126., 129., 132., 135., 138., 141., 144., 147., 150.],
       [153., 156., 159., 162., 165., 168., 171., 174., 177., 180.],
       [183., 186., 189., 192., 195., 198., 201., 204., 207., 210.],
       [213., 216., 219., 222., 225., 228., 231., 234., 237., 240.],
       [243., 246., 249., 252., 255., 258., 261., 264., 267., 270.],
       [273., 276., 279., 282., 285., 288., 291., 294., 297., 300.]])