In [14]:
# Inport numpy
import numpy as np

In [20]:
def normalize(x):
    a = x.std()
    b = x.mean()
    z = x-b/a
    return z

In [21]:
x = np.random.random((5, 5))
x

array([[0.40266197, 0.22500075, 0.34011694, 0.60104316, 0.14696201],
       [0.28170881, 0.34368189, 0.05909495, 0.9072565 , 0.20064451],
       [0.68392806, 0.89509632, 0.89221718, 0.15614357, 0.78945963],
       [0.238619  , 0.49122899, 0.63103188, 0.37366996, 0.30273862],
       [0.03601148, 0.99039652, 0.98838868, 0.0754882 , 0.77252596]])

In [22]:
s = normalize(x)
s

array([[-1.12898825, -1.30664946, -1.19153328, -0.93060706, -1.38468821],
       [-1.24994141, -1.18796832, -1.47255527, -0.62439372, -1.33100571],
       [-0.84772215, -0.63655389, -0.63943303, -1.37550664, -0.74219059],
       [-1.29303122, -1.04042123, -0.90061834, -1.15798026, -1.2289116 ],
       [-1.49563874, -0.54125369, -0.54326154, -1.45616201, -0.75912426]])

In [23]:
np.save('X_normalize.npy', s)

In [24]:
f = np.load('X_normalize.npy')
f

array([[-1.12898825, -1.30664946, -1.19153328, -0.93060706, -1.38468821],
       [-1.24994141, -1.18796832, -1.47255527, -0.62439372, -1.33100571],
       [-0.84772215, -0.63655389, -0.63943303, -1.37550664, -0.74219059],
       [-1.29303122, -1.04042123, -0.90061834, -1.15798026, -1.2289116 ],
       [-1.49563874, -0.54125369, -0.54326154, -1.45616201, -0.75912426]])