In [15]:
import numpy as np

In [17]:
def normalize(x):
    a = x.std()
    b = x.mean()
    z = x-b/a
    return z

In [19]:
x = np.random.random((5, 5))
x

array([[0.04737942, 0.34596727, 0.97595246, 0.30692033, 0.89854362],
       [0.62113428, 0.2663641 , 0.67874091, 0.73118754, 0.67105294],
       [0.12692789, 0.37452148, 0.74964501, 0.47188613, 0.38531168],
       [0.11871023, 0.92416689, 0.21504281, 0.88777259, 0.98703411],
       [0.27982175, 0.16362243, 0.44505019, 0.94756094, 0.57150943]])

In [21]:
s = normalize(x)
s

array([[-1.72683751, -1.42824966, -0.79826447, -1.4672966 , -0.8756733 ],
       [-1.15308264, -1.50785283, -1.09547602, -1.04302938, -1.10316399],
       [-1.64728903, -1.39969545, -1.02457192, -1.3023308 , -1.38890525],
       [-1.65550669, -0.85005004, -1.55917411, -0.88644434, -0.78718281],
       [-1.49439517, -1.61059449, -1.32916674, -0.82665598, -1.2027075 ]])

In [23]:
np.save('X_normalize.npy', s)

In [25]:
f = np.load('X_normalize.npy')
f

array([[-1.72683751, -1.42824966, -0.79826447, -1.4672966 , -0.8756733 ],
       [-1.15308264, -1.50785283, -1.09547602, -1.04302938, -1.10316399],
       [-1.64728903, -1.39969545, -1.02457192, -1.3023308 , -1.38890525],
       [-1.65550669, -0.85005004, -1.55917411, -0.88644434, -0.78718281],
       [-1.49439517, -1.61059449, -1.32916674, -0.82665598, -1.2027075 ]])