In [25]:
# Import numpy
import numpy as np

In [26]:
# Create a function for normalization
def normalize(x):
    a = x.std()
    b = x.mean()
    z = x-b/a
    return z

In [27]:
# Random a 10 x 10 array
x = np.random.random((5, 5))
x

array([[0.2527947 , 0.37921064, 0.90028514, 0.55894666, 0.3202707 ],
       [0.82419242, 0.06452178, 0.30270766, 0.5442469 , 0.6217257 ],
       [0.18074949, 0.46388966, 0.70720355, 0.2543343 , 0.35881029],
       [0.62920532, 0.71497163, 0.10017392, 0.74361683, 0.78720077],
       [0.18616163, 0.96436112, 0.91484265, 0.46667248, 0.72549152]])

In [28]:
# Normalize the array
s = normalize(x)
s

array([[-1.71169211, -1.58527617, -1.06420167, -1.40554015, -1.64421611],
       [-1.14029439, -1.89996503, -1.66177915, -1.42023991, -1.34276111],
       [-1.78373732, -1.50059715, -1.25728326, -1.71015251, -1.60567652],
       [-1.33528149, -1.24951518, -1.86431289, -1.22086998, -1.17728604],
       [-1.77832517, -1.00012568, -1.04964416, -1.49781433, -1.23899529]])

In [29]:
# save the file for normalized array
np.save('X_normalize.npy', s)

In [30]:
# Check if the array is saved using np.load
f = np.load('X_normalize.npy')
f

array([[-1.71169211, -1.58527617, -1.06420167, -1.40554015, -1.64421611],
       [-1.14029439, -1.89996503, -1.66177915, -1.42023991, -1.34276111],
       [-1.78373732, -1.50059715, -1.25728326, -1.71015251, -1.60567652],
       [-1.33528149, -1.24951518, -1.86431289, -1.22086998, -1.17728604],
       [-1.77832517, -1.00012568, -1.04964416, -1.49781433, -1.23899529]])